# Generated by Django 2.0.6 on 2018-07-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.FloatField(help_text='Rs 5000')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(help_text='Please enter the course name', max_length=128)),
                ('fees', models.FloatField(help_text='Rs 5000')),
                ('coursediscount', models.IntegerField(help_text='eg: 12 %')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='CourseDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Please enter the full name', max_length=128)),
                ('adress', models.SlugField(help_text='Nayabazar,kathmandu')),
                ('contactno', models.CharField(help_text='9818204111', max_length=128)),
                ('email', models.EmailField(help_text='mydomain@gmail.com', max_length=128)),
                ('fees', models.FloatField(help_text='Rs 5000')),
                ('dob', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')])),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_app.Enquiry')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Please enter the full name', max_length=128)),
                ('adress', models.SlugField(help_text='Nayabazar,kathmandu')),
                ('contactno', models.CharField(help_text='9818204111', max_length=128)),
                ('email', models.EmailField(blank=True, help_text='mydomain@gmail.com', max_length=128, null=True)),
                ('fees', models.FloatField(help_text='Rs 5000')),
                ('bonus', models.FloatField(help_text='Rs 5000')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseduration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_app.CourseDuration'),
        ),
        migrations.AddField(
            model_name='booking',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_app.Course'),
        ),
        migrations.AddField(
            model_name='booking',
            name='enquiryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_app.Enquiry'),
        ),
    ]
