# Generated by Django 2.0.6 on 2018-07-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseduration',
            old_name='coursename',
            new_name='courseduration',
        ),
    ]
