# Generated by Django 2.0.6 on 2018-07-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_app', '0002_auto_20180704_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='adress',
            field=models.TextField(help_text='Nayabazar,kathmandu'),
        ),
    ]
